# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Disable build features we don't use
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false
